server:
  port: 8080

spring:
  application:
    name: student-cert-verifier
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/scv}

file:
  storageDir: ${FILE_STORAGE_DIR:uploads}

web3:
  rpcUrl: ${WEB3_RPC_URL:https://rpc-amoy.polygon.technology}
  privateKey: ${WEB3_PRIVATE_KEY:replace_with_private_key}
  chainId: ${WEB3_CHAIN_ID:80002}
  contractAddress: ${CONTRACT_ADDRESS:0x0000000000000000000000000000000000000000}
  gas:
    maxFeeGwei: ${WEB3_MAX_FEE_GWEI:50}
    priorityFeeGwei: ${WEB3_PRIORITY_FEE_GWEI:30}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
